-- CRIACAO DO DATASET_COM O JOIN ENTRE PRE_ANALITICO E GLOBAL_PRODUCAO

SELECT pa.ID_PEDIDO, -- (LIGACAO)
	pa.ID_UNIDADE, -- (LIGACAO)
	pa.MNEMONICO, -- (LIGACAO)
	pa.TIPO_MATERIAL, -- (LIGACAO)
	pa.DATA_ENTREGA_STC,
	pa.DATA_PEDIDO,
	pa.SEXO_PACIENTE,
	pa.DESTINO_AMOSTRA,
	gp.DATA_LIBERACAO,
	gp.QTDE_DE_AMOSTRA,
	gp.UF_DO_CLIENTE,
	gp.CIDADE_DO_CLIENTE,
	gp.IDADE_DO_CLIENTE,
	gp.CÓD_CENTRO_DE_CUSTO,
	gp.QTDE_REMARCACAO,
	gp.QTDE_RECOLETA,
	gp.QTDE_RESET,
	gp.QTDE_RETIFICACAO
INTO QUESTAO_2
FROM PRE_ANALITICO pa
INNER JOIN GLOBAL_PRODUCAO gp
ON (pa.ID_PEDIDO = gp.ID_PEDIDO 
AND pa.ID_UNIDADE = gp.ID_UNIDADE
AND pa.MNEMONICO = gp.MNEMONICO
AND pa.TIPO_MATERIAL = gp.TIPO_MATERIAL)

-- CHECK DUPLICIDADE 

SELECT COUNT(*) FROM QUESTAO_2

SELECT COUNT(*) FROM (
SELECT DISTINCT ID_PEDIDO, -- (LIGACAO)
				ID_UNIDADE, -- (LIGACAO)
				MNEMONICO, -- (LIGACAO)
				TIPO_MATERIAL, -- (LIGACAO)
				DATA_ENTREGA_STC,
				DATA_PEDIDO,
				SEXO_PACIENTE,
				DESTINO_AMOSTRA,
				DATA_LIBERACAO,
				QTDE_DE_AMOSTRA,
				UF_DO_CLIENTE,
				CIDADE_DO_CLIENTE,
				IDADE_DO_CLIENTE,
				CÓD_CENTRO_DE_CUSTO,
				QTDE_REMARCACAO,
				QTDE_RECOLETA,
				QTDE_RESET,
				QTDE_RETIFICACAO  FROM QUESTAO_2) QTD


-- ANALISE POR REGIAO POR PEDIDOS

SELECT UF_DO_CLIENTE,
CIDADE_DO_CLIENTE,
COUNT(DISTINCT ID_PEDIDO) AS QTD_PEDIDOS
FROM QUESTAO_2
GROUP BY 
UF_DO_CLIENTE,
CIDADE_DO_CLIENTE
ORDER BY QTD_PEDIDOS DESC

-- ANALISE POR REGIAO POR UNIDADES

SELECT UF_DO_CLIENTE,
CIDADE_DO_CLIENTE,
COUNT(DISTINCT ID_UNIDADE) AS QTD_UNIDADES
FROM QUESTAO_2
GROUP BY 
UF_DO_CLIENTE,
CIDADE_DO_CLIENTE
ORDER BY QTD_UNIDADES DESC

-- ANALISE POR DESTINO AMOSTRA POR PEDIDO

SELECT DESTINO_AMOSTRA,
COUNT(DISTINCT ID_PEDIDO) AS QTD_PEDIDOS_AMOSTRA
FROM QUESTAO_2
GROUP BY 
DESTINO_AMOSTRA
ORDER BY QTD_PEDIDOS_AMOSTRA DESC


-- CALCULAR A DIFERENÇA ENTRE DATA_ENTREGA E PEDIDO

SELECT ID_PEDIDO,
	   ID_UNIDADE,
	   DATA_PEDIDO,
	   DATA_ENTREGA_STC,
	   DATEDIFF(day, DATA_PEDIDO, DATA_ENTREGA_STC) AS  DIFF_DATAS
FROM QUESTAO_2


-- CALCULAR A O TEMPO MEDIO DE DIFERENÇA ENTRE DATA_ENTREGA E PEDIDO POR PEDIDO

SELECT AVG(DIFF_DATAS) AS MEDIA_TEMPO_ENTREGA,
	   MAX(DIFF_DATAS) AS MAX_TEMPO_ENTREGA,
	   MIN(DIFF_DATAS) AS MIN_TEMPO_ENTREGA
FROM (
SELECT DISTINCT ID_PEDIDO,
	   ID_UNIDADE,
	   DATA_PEDIDO,
	   DATA_ENTREGA_STC,
	   DATEDIFF(day, DATA_PEDIDO, DATA_ENTREGA_STC) AS  DIFF_DATAS
FROM QUESTAO_2 ) HELP

